### ISSUE TITLE
We need unit tests!

### ISSUE THREAD

**Issue by needcaffeine** [needcaffeine/yakdb#7]

**Comment by keelerm84** [comment]
I have started working on this one.  I figure I won't have time to finish it this morning, but I wanted to make sure we weren't duplicating work.  :smile:  Thanks!

**Comment by needcaffeine** [comment]
Yay! I did start, but I haven't gotten anywhere, so I'll stop.

**Comment by needcaffeine** [comment]
Going to call this one done. Thanks @keelerm84!
